# Generated by Django 4.1.2 on 2023-07-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnb',
            name='image',
            field=models.ImageField(upload_to='bnb/rental/bnb_images'),
        ),
    ]
